name: ivohofland
favicon: null
layout_spectrum: 0
typography_spectrum: 0.42042
title: ivohofland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#cecece'
    - '#a8a8a8'
    - '#888888'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
